# SPDX-License-Identifier: Apache-2.0

# Copyright 2021 PANTHEON.tech
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
vppConfig:
  # Physical interfaces.
  interfaces:
    - name: gbe-private-net
      type: DPDK
      enabled: true
      ipAddresses:
        # (!) Change the example private IP range to the actual value before deploying:
        - 192.168.1.1/24

    - name: gbe-public-net
      type: DPDK
      enabled: true
      ipAddresses:
        # (!) Change the example public IP range to the actual value before deploying:
        - 80.80.80.1/24

  # Default route.
  routes:
    - dstNetwork: 0.0.0.0/0
      # (!) Change from the example to the actual next hop IP address before deploying:
      nextHopAddr: 80.80.80.2
      outgoingInterface: gbe-public-net
