// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: srv6.proto

package linux_srv6

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LocalSID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid    string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	// Types that are assignable to EndFunction:
	//	*LocalSID_BaseEndFunction
	//	*LocalSID_EndFunctionX
	//	*LocalSID_EndFunctionT
	//	*LocalSID_EndFunctionDx2
	//	*LocalSID_EndFunctionDx4
	//	*LocalSID_EndFunctionDx6
	//	*LocalSID_EndFunctionDt4
	//	*LocalSID_EndFunctionDt6
	//	*LocalSID_EndFunctionB6
	//	*LocalSID_EndFunctionB6Encaps
	EndFunction isLocalSID_EndFunction `protobuf_oneof:"end_function"`
}

func (x *LocalSID) Reset() {
	*x = LocalSID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID) ProtoMessage() {}

func (x *LocalSID) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID.ProtoReflect.Descriptor instead.
func (*LocalSID) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0}
}

func (x *LocalSID) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *LocalSID) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (m *LocalSID) GetEndFunction() isLocalSID_EndFunction {
	if m != nil {
		return m.EndFunction
	}
	return nil
}

func (x *LocalSID) GetBaseEndFunction() *LocalSID_End {
	if x, ok := x.GetEndFunction().(*LocalSID_BaseEndFunction); ok {
		return x.BaseEndFunction
	}
	return nil
}

func (x *LocalSID) GetEndFunctionX() *LocalSID_EndX {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionX); ok {
		return x.EndFunctionX
	}
	return nil
}

func (x *LocalSID) GetEndFunctionT() *LocalSID_EndT {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionT); ok {
		return x.EndFunctionT
	}
	return nil
}

func (x *LocalSID) GetEndFunctionDx2() *LocalSID_EndDX2 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionDx2); ok {
		return x.EndFunctionDx2
	}
	return nil
}

func (x *LocalSID) GetEndFunctionDx4() *LocalSID_EndDX4 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionDx4); ok {
		return x.EndFunctionDx4
	}
	return nil
}

func (x *LocalSID) GetEndFunctionDx6() *LocalSID_EndDX6 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionDx6); ok {
		return x.EndFunctionDx6
	}
	return nil
}

func (x *LocalSID) GetEndFunctionDt4() *LocalSID_EndDT4 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionDt4); ok {
		return x.EndFunctionDt4
	}
	return nil
}

func (x *LocalSID) GetEndFunctionDt6() *LocalSID_EndDT6 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionDt6); ok {
		return x.EndFunctionDt6
	}
	return nil
}

func (x *LocalSID) GetEndFunctionB6() *LocalSID_EndB6 {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionB6); ok {
		return x.EndFunctionB6
	}
	return nil
}

func (x *LocalSID) GetEndFunctionB6Encaps() *LocalSID_EndB6Encaps {
	if x, ok := x.GetEndFunction().(*LocalSID_EndFunctionB6Encaps); ok {
		return x.EndFunctionB6Encaps
	}
	return nil
}

type isLocalSID_EndFunction interface {
	isLocalSID_EndFunction()
}

type LocalSID_BaseEndFunction struct {
	BaseEndFunction *LocalSID_End `protobuf:"bytes,3,opt,name=base_end_function,json=baseEndFunction,proto3,oneof"`
}

type LocalSID_EndFunctionX struct {
	EndFunctionX *LocalSID_EndX `protobuf:"bytes,4,opt,name=end_function_x,json=endFunctionX,proto3,oneof"`
}

type LocalSID_EndFunctionT struct {
	EndFunctionT *LocalSID_EndT `protobuf:"bytes,5,opt,name=end_function_t,json=endFunctionT,proto3,oneof"`
}

type LocalSID_EndFunctionDx2 struct {
	EndFunctionDx2 *LocalSID_EndDX2 `protobuf:"bytes,6,opt,name=end_function_dx2,json=endFunctionDx2,proto3,oneof"`
}

type LocalSID_EndFunctionDx4 struct {
	EndFunctionDx4 *LocalSID_EndDX4 `protobuf:"bytes,7,opt,name=end_function_dx4,json=endFunctionDx4,proto3,oneof"`
}

type LocalSID_EndFunctionDx6 struct {
	EndFunctionDx6 *LocalSID_EndDX6 `protobuf:"bytes,8,opt,name=end_function_dx6,json=endFunctionDx6,proto3,oneof"`
}

type LocalSID_EndFunctionDt4 struct {
	EndFunctionDt4 *LocalSID_EndDT4 `protobuf:"bytes,9,opt,name=end_function_dt4,json=endFunctionDt4,proto3,oneof"`
}

type LocalSID_EndFunctionDt6 struct {
	EndFunctionDt6 *LocalSID_EndDT6 `protobuf:"bytes,10,opt,name=end_function_dt6,json=endFunctionDt6,proto3,oneof"`
}

type LocalSID_EndFunctionB6 struct {
	EndFunctionB6 *LocalSID_EndB6 `protobuf:"bytes,11,opt,name=end_function_b6,json=endFunctionB6,proto3,oneof"`
}

type LocalSID_EndFunctionB6Encaps struct {
	EndFunctionB6Encaps *LocalSID_EndB6Encaps `protobuf:"bytes,12,opt,name=end_function_b6_encaps,json=endFunctionB6Encaps,proto3,oneof"`
}

func (*LocalSID_BaseEndFunction) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionX) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionT) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionDx2) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionDx4) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionDx6) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionDt4) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionDt6) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionB6) isLocalSID_EndFunction() {}

func (*LocalSID_EndFunctionB6Encaps) isLocalSID_EndFunction() {}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix    string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	EncapMode string   `protobuf:"bytes,2,opt,name=encapMode,proto3" json:"encapMode,omitempty"`
	Segments  []string `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	KeyId     string   `protobuf:"bytes,4,opt,name=keyId,proto3" json:"keyId,omitempty"`
	Device    string   `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Policy) GetEncapMode() string {
	if x != nil {
		return x.EncapMode
	}
	return ""
}

func (x *Policy) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Policy) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Policy) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type BlackHoleRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TableId uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *BlackHoleRoute) Reset() {
	*x = BlackHoleRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackHoleRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackHoleRoute) ProtoMessage() {}

func (x *BlackHoleRoute) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackHoleRoute.ProtoReflect.Descriptor instead.
func (*BlackHoleRoute) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{2}
}

func (x *BlackHoleRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlackHoleRoute) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

type PolicyRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix  string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TableId uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyRule) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PolicyRule) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

type SRv6Global struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	KeyId     string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm string `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
}

func (x *SRv6Global) Reset() {
	*x = SRv6Global{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRv6Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRv6Global) ProtoMessage() {}

func (x *SRv6Global) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRv6Global.ProtoReflect.Descriptor instead.
func (*SRv6Global) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{4}
}

func (x *SRv6Global) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SRv6Global) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SRv6Global) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SRv6Global) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type LocalSID_End struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LocalSID_End) Reset() {
	*x = LocalSID_End{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_End) ProtoMessage() {}

func (x *LocalSID_End) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_End.ProtoReflect.Descriptor instead.
func (*LocalSID_End) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 0}
}

type LocalSID_EndX struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextHop string `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
}

func (x *LocalSID_EndX) Reset() {
	*x = LocalSID_EndX{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndX) ProtoMessage() {}

func (x *LocalSID_EndX) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndX.ProtoReflect.Descriptor instead.
func (*LocalSID_EndX) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LocalSID_EndX) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

type LocalSID_EndT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfId uint32 `protobuf:"varint,1,opt,name=vrf_id,json=vrfId,proto3" json:"vrf_id,omitempty"`
}

func (x *LocalSID_EndT) Reset() {
	*x = LocalSID_EndT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndT) ProtoMessage() {}

func (x *LocalSID_EndT) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndT.ProtoReflect.Descriptor instead.
func (*LocalSID_EndT) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 2}
}

func (x *LocalSID_EndT) GetVrfId() uint32 {
	if x != nil {
		return x.VrfId
	}
	return 0
}

type LocalSID_EndDX2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutgoingInterface string `protobuf:"bytes,1,opt,name=outgoing_interface,json=outgoingInterface,proto3" json:"outgoing_interface,omitempty"`
}

func (x *LocalSID_EndDX2) Reset() {
	*x = LocalSID_EndDX2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndDX2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndDX2) ProtoMessage() {}

func (x *LocalSID_EndDX2) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndDX2.ProtoReflect.Descriptor instead.
func (*LocalSID_EndDX2) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 3}
}

func (x *LocalSID_EndDX2) GetOutgoingInterface() string {
	if x != nil {
		return x.OutgoingInterface
	}
	return ""
}

type LocalSID_EndDX4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextHop string `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
}

func (x *LocalSID_EndDX4) Reset() {
	*x = LocalSID_EndDX4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndDX4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndDX4) ProtoMessage() {}

func (x *LocalSID_EndDX4) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndDX4.ProtoReflect.Descriptor instead.
func (*LocalSID_EndDX4) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 4}
}

func (x *LocalSID_EndDX4) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

type LocalSID_EndDX6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextHop string `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
}

func (x *LocalSID_EndDX6) Reset() {
	*x = LocalSID_EndDX6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndDX6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndDX6) ProtoMessage() {}

func (x *LocalSID_EndDX6) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndDX6.ProtoReflect.Descriptor instead.
func (*LocalSID_EndDX6) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 5}
}

func (x *LocalSID_EndDX6) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

type LocalSID_EndDT4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfId uint32 `protobuf:"varint,1,opt,name=vrf_id,json=vrfId,proto3" json:"vrf_id,omitempty"`
}

func (x *LocalSID_EndDT4) Reset() {
	*x = LocalSID_EndDT4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndDT4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndDT4) ProtoMessage() {}

func (x *LocalSID_EndDT4) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndDT4.ProtoReflect.Descriptor instead.
func (*LocalSID_EndDT4) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 6}
}

func (x *LocalSID_EndDT4) GetVrfId() uint32 {
	if x != nil {
		return x.VrfId
	}
	return 0
}

type LocalSID_EndDT6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfId uint32 `protobuf:"varint,1,opt,name=vrf_id,json=vrfId,proto3" json:"vrf_id,omitempty"`
}

func (x *LocalSID_EndDT6) Reset() {
	*x = LocalSID_EndDT6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndDT6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndDT6) ProtoMessage() {}

func (x *LocalSID_EndDT6) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndDT6.ProtoReflect.Descriptor instead.
func (*LocalSID_EndDT6) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 7}
}

func (x *LocalSID_EndDT6) GetVrfId() uint32 {
	if x != nil {
		return x.VrfId
	}
	return 0
}

type LocalSID_EndB6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []string `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	KeyId    string   `protobuf:"bytes,2,opt,name=keyId,proto3" json:"keyId,omitempty"`
}

func (x *LocalSID_EndB6) Reset() {
	*x = LocalSID_EndB6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndB6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndB6) ProtoMessage() {}

func (x *LocalSID_EndB6) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndB6.ProtoReflect.Descriptor instead.
func (*LocalSID_EndB6) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 8}
}

func (x *LocalSID_EndB6) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *LocalSID_EndB6) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type LocalSID_EndB6Encaps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []string `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	KeyId    string   `protobuf:"bytes,2,opt,name=keyId,proto3" json:"keyId,omitempty"`
}

func (x *LocalSID_EndB6Encaps) Reset() {
	*x = LocalSID_EndB6Encaps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srv6_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalSID_EndB6Encaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalSID_EndB6Encaps) ProtoMessage() {}

func (x *LocalSID_EndB6Encaps) ProtoReflect() protoreflect.Message {
	mi := &file_srv6_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalSID_EndB6Encaps.ProtoReflect.Descriptor instead.
func (*LocalSID_EndB6Encaps) Descriptor() ([]byte, []int) {
	return file_srv6_proto_rawDescGZIP(), []int{0, 9}
}

func (x *LocalSID_EndB6Encaps) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *LocalSID_EndB6Encaps) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_srv6_proto protoreflect.FileDescriptor

var file_srv6_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x22, 0xa8, 0x09, 0x0a, 0x08, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x53, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x46, 0x0a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44,
	0x2e, 0x45, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x45, 0x6e, 0x64, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x5f, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x58, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x6e,
	0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x41, 0x0a, 0x0e, 0x65, 0x6e,
	0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x54, 0x48, 0x00, 0x52,
	0x0c, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x12, 0x47, 0x0a,
	0x10, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x78,
	0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e,
	0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e,
	0x64, 0x44, 0x58, 0x32, 0x48, 0x00, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x78, 0x32, 0x12, 0x47, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x78, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x44, 0x58, 0x34, 0x48, 0x00, 0x52,
	0x0e, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x78, 0x34, 0x12,
	0x47, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x78, 0x36, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x75,
	0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e,
	0x45, 0x6e, 0x64, 0x44, 0x58, 0x36, 0x48, 0x00, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x78, 0x36, 0x12, 0x47, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x74, 0x34, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x44, 0x54, 0x34, 0x48,
	0x00, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x74,
	0x34, 0x12, 0x47, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x64, 0x74, 0x36, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49,
	0x44, 0x2e, 0x45, 0x6e, 0x64, 0x44, 0x54, 0x36, 0x48, 0x00, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x74, 0x36, 0x12, 0x44, 0x0a, 0x0f, 0x65, 0x6e,
	0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x36, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x42, 0x36, 0x48,
	0x00, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x36,
	0x12, 0x57, 0x0a, 0x16, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x62, 0x36, 0x5f, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2e, 0x73, 0x72, 0x76, 0x36, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x53, 0x49, 0x44, 0x2e, 0x45, 0x6e, 0x64, 0x42, 0x36, 0x45, 0x6e, 0x63, 0x61,
	0x70, 0x73, 0x48, 0x00, 0x52, 0x13, 0x65, 0x6e, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x36, 0x45, 0x6e, 0x63, 0x61, 0x70, 0x73, 0x1a, 0x05, 0x0a, 0x03, 0x45, 0x6e, 0x64,
	0x1a, 0x21, 0x0a, 0x04, 0x45, 0x6e, 0x64, 0x58, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x5f, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x78, 0x74,
	0x48, 0x6f, 0x70, 0x1a, 0x1d, 0x0a, 0x04, 0x45, 0x6e, 0x64, 0x54, 0x12, 0x15, 0x0a, 0x06, 0x76,
	0x72, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x72, 0x66,
	0x49, 0x64, 0x1a, 0x37, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x44, 0x58, 0x32, 0x12, 0x2d, 0x0a, 0x12,
	0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0x23, 0x0a, 0x06, 0x45,
	0x6e, 0x64, 0x44, 0x58, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x48, 0x6f, 0x70,
	0x1a, 0x23, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x44, 0x58, 0x36, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x78, 0x74, 0x48, 0x6f, 0x70, 0x1a, 0x1f, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x44, 0x54, 0x34, 0x12,
	0x15, 0x0a, 0x06, 0x76, 0x72, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x76, 0x72, 0x66, 0x49, 0x64, 0x1a, 0x1f, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x44, 0x54, 0x36,
	0x12, 0x15, 0x0a, 0x06, 0x76, 0x72, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x76, 0x72, 0x66, 0x49, 0x64, 0x1a, 0x39, 0x0a, 0x05, 0x45, 0x6e, 0x64, 0x42, 0x36,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79,
	0x49, 0x64, 0x1a, 0x3f, 0x0a, 0x0b, 0x45, 0x6e, 0x64, 0x42, 0x36, 0x45, 0x6e, 0x63, 0x61, 0x70,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x65, 0x6e, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x61, 0x70, 0x4d,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x61, 0x70,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x3f,
	0x0a, 0x0e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x3f, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x6f, 0x0a, 0x0a, 0x53, 0x52, 0x76, 0x36, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x6f, 0x2e, 0x70, 0x61, 0x6e, 0x74, 0x68, 0x65, 0x6f, 0x6e,
	0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x2f, 0x73, 0x72, 0x76, 0x36,
	0x3b, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x5f, 0x73, 0x72, 0x76, 0x36, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_srv6_proto_rawDescOnce sync.Once
	file_srv6_proto_rawDescData = file_srv6_proto_rawDesc
)

func file_srv6_proto_rawDescGZIP() []byte {
	file_srv6_proto_rawDescOnce.Do(func() {
		file_srv6_proto_rawDescData = protoimpl.X.CompressGZIP(file_srv6_proto_rawDescData)
	})
	return file_srv6_proto_rawDescData
}

var file_srv6_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_srv6_proto_goTypes = []interface{}{
	(*LocalSID)(nil),             // 0: linux.srv6.LocalSID
	(*Policy)(nil),               // 1: linux.srv6.Policy
	(*BlackHoleRoute)(nil),       // 2: linux.srv6.BlackHoleRoute
	(*PolicyRule)(nil),           // 3: linux.srv6.PolicyRule
	(*SRv6Global)(nil),           // 4: linux.srv6.SRv6Global
	(*LocalSID_End)(nil),         // 5: linux.srv6.LocalSID.End
	(*LocalSID_EndX)(nil),        // 6: linux.srv6.LocalSID.EndX
	(*LocalSID_EndT)(nil),        // 7: linux.srv6.LocalSID.EndT
	(*LocalSID_EndDX2)(nil),      // 8: linux.srv6.LocalSID.EndDX2
	(*LocalSID_EndDX4)(nil),      // 9: linux.srv6.LocalSID.EndDX4
	(*LocalSID_EndDX6)(nil),      // 10: linux.srv6.LocalSID.EndDX6
	(*LocalSID_EndDT4)(nil),      // 11: linux.srv6.LocalSID.EndDT4
	(*LocalSID_EndDT6)(nil),      // 12: linux.srv6.LocalSID.EndDT6
	(*LocalSID_EndB6)(nil),       // 13: linux.srv6.LocalSID.EndB6
	(*LocalSID_EndB6Encaps)(nil), // 14: linux.srv6.LocalSID.EndB6Encaps
}
var file_srv6_proto_depIdxs = []int32{
	5,  // 0: linux.srv6.LocalSID.base_end_function:type_name -> linux.srv6.LocalSID.End
	6,  // 1: linux.srv6.LocalSID.end_function_x:type_name -> linux.srv6.LocalSID.EndX
	7,  // 2: linux.srv6.LocalSID.end_function_t:type_name -> linux.srv6.LocalSID.EndT
	8,  // 3: linux.srv6.LocalSID.end_function_dx2:type_name -> linux.srv6.LocalSID.EndDX2
	9,  // 4: linux.srv6.LocalSID.end_function_dx4:type_name -> linux.srv6.LocalSID.EndDX4
	10, // 5: linux.srv6.LocalSID.end_function_dx6:type_name -> linux.srv6.LocalSID.EndDX6
	11, // 6: linux.srv6.LocalSID.end_function_dt4:type_name -> linux.srv6.LocalSID.EndDT4
	12, // 7: linux.srv6.LocalSID.end_function_dt6:type_name -> linux.srv6.LocalSID.EndDT6
	13, // 8: linux.srv6.LocalSID.end_function_b6:type_name -> linux.srv6.LocalSID.EndB6
	14, // 9: linux.srv6.LocalSID.end_function_b6_encaps:type_name -> linux.srv6.LocalSID.EndB6Encaps
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_srv6_proto_init() }
func file_srv6_proto_init() {
	if File_srv6_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_srv6_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackHoleRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRv6Global); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_End); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndX); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndDX2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndDX4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndDX6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndDT4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndDT6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndB6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_srv6_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalSID_EndB6Encaps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_srv6_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LocalSID_BaseEndFunction)(nil),
		(*LocalSID_EndFunctionX)(nil),
		(*LocalSID_EndFunctionT)(nil),
		(*LocalSID_EndFunctionDx2)(nil),
		(*LocalSID_EndFunctionDx4)(nil),
		(*LocalSID_EndFunctionDx6)(nil),
		(*LocalSID_EndFunctionDt4)(nil),
		(*LocalSID_EndFunctionDt6)(nil),
		(*LocalSID_EndFunctionB6)(nil),
		(*LocalSID_EndFunctionB6Encaps)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_srv6_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_srv6_proto_goTypes,
		DependencyIndexes: file_srv6_proto_depIdxs,
		MessageInfos:      file_srv6_proto_msgTypes,
	}.Build()
	File_srv6_proto = out.File
	file_srv6_proto_rawDesc = nil
	file_srv6_proto_goTypes = nil
	file_srv6_proto_depIdxs = nil
}
